### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by shaqq** [gottfrois/grape-attack#1]
Hi there, saw this on Ruby Weekly. Looks cool!

Would you consider providing some documentation on how this works? At first glance, it seems like it's counting the requests in memory. How would that work in app servers that are, often, multi-thread or multi-process? Examples are Unicorn, Puma, and Passenger.

**Comment by gottfrois** [comment]
Hey thx !

Mutli-process servers should not be an issue but the counter will be global across all servers. If the endpoint has 100 requests allowed, no matter how the requests are distributed across the processes, only 100 in total would be allowed.

Now, regarding mutli-threaded servers, it's a good question. I think I need to some fixes to make sure the connection with the broker (redis by default) is threadsafe. I'll have a closer look.

How it works is pretty simple. Each time we hit the endpoint, we increment a counter by one. We also expire that counter in time using redis expired values.

**Comment by shaqq** [comment]
ah i see, i didn't realize that the counter was in Redis, or elsewhere outside the application.

thanks!
