### ISSUE TITLE
how to gracefully handle this error - Grape::Attack::RateLimitExceededError 

### ISSUE THREAD

**Issue by shanmugavela** [gottfrois/grape-attack#13]
Hi,

How to gracefully handle this error - Grape::Attack::RateLimitExceededError. Its increasing error rate on newrelic. 

Anybody facing the same issue?

Thanks,
Shan

**Comment by gottfrois** [comment]
You probably want to catch it and notify your client about it

**Comment by shanmugavela** [comment]
I would like to catch it, its unnecessarily increasing error rate

**Comment by gottfrois** [comment]
Have you tried something like this?

``` ruby
rescue_from Grape::Attack::RateLimitExceededError do |e|
  # do something
end
```

**Comment by shanmugavela** [comment]
We are already doing this, still in newrelic we are getting the below error:

Error message
Grape::Attack::RateLimitExceededError: API rate limit exceeded for 127.0.0.1.

Our code:
rescue_from Grape::Attack::RateLimitExceededError do |e|
        error!({errors: {error_code: '403', error_message: 'API rate limit exceeded'}}, 403)
      end

**Comment by gottfrois** [comment]
That probably means newrelic is catching the error before the `rescue_from`. Can't help you much here
