### ISSUE TITLE
How does it compare to Rack::Attack?

### ISSUE THREAD

**Issue by janko** [gottfrois/grape-attack#2]
From the readme, it seems like this gem is doing something very similar to [Rack::Attack](https://github.com/kickstarter/rack-attack). Since Rack::Attack is an already well-known gem, and it can be used in _any_ Rack application (not just for Grape), I think it wold be good to add to the readme what are some of the advantages of using Grape::Attack over Rack::Attack in Grape applications.

**Comment by gottfrois** [comment]
Yes good idea. Basically I considered using rack-attack for my own usage but I wanted something with a custom DSL for each of my grape endpoints. I also did not really care about white/black listing (yet). Finally I wanted to set custom HTTP headers with api limit values and usage.
