### ISSUE TITLE
A question

### ISSUE THREAD

**Issue by confact** [gottfrois/grape-attack#4]
I am using Grape for my API and wonder if it is anyway to use this and have different throttling rules for different types of users. Based on if they are VIP or not.

Do you know I can do that?

**Comment by gottfrois** [comment]
Currently no, but I'm going to need this functionality as well for my APIs :) I'm not sure yet what would be the api for this, any thoughts?

**Comment by gottfrois** [comment]
An easy solution would be to allow to pass `proc` instead of numbers in the `max` and `per` definition.

**Comment by confact** [comment]
@gottfrois okay, thanks. i will try that. Another question.

Does it exist a way to get remaining request for viewing on the rails app? 
Also, is it a way to have one limit for all endpoints? Now it seems to be set for each endpoint, but i want as say 3000 total for all endpoints together.

**Comment by gottfrois** [comment]
> Does it exist a way to get remaining request for viewing on the rails app? 

You have the following http header:

X-RateLimit-Remaining -- The number of requests remaining in the current rate limit window.

> Also, is it a way to have one limit for all endpoints? Now it seems to be set for each endpoint, but i want as say 3000 total for all endpoints together.

Not really no, limits are per end-points for the moment.

**Comment by pbssubhash** [comment]
@gottfrois , How do I implement this using Proc? Assuming I've user_role : 1 or 2 in the User model, I want to throttle the requests differently for different users. How can I do this using Proc? 

Appreciate any help.
Thanks.

**Comment by gottfrois** [comment]
Try this but I doubt it will work. I currently don't handle proc but it should be easy to do so a PR is welcome :)

``` ruby
throttle max: Proc.new { 100 }, per: 1.day
```

**Comment by pbssubhash** [comment]
Is this fixed now? If yes great!
How can we impelemnt this?
