### ISSUE TITLE
TypeError (no implicit conversion of String into Integer):

### ISSUE THREAD

**Issue by vijay22** [gottfrois/grape-attack#9]
When response is empty and adding only status code -
status :no_content OR status 204

Getting below error -

TypeError (no implicit conversion of String into Integer):
  grape-attack (0.2.0) lib/grape/attack/throttle.rb:20:in `[]='
  grape-attack (0.2.0) lib/grape/attack/throttle.rb:20:in`after'
  grape (0.14.0) lib/grape/middleware/base.rb:26:in `call!'
  grape (0.14.0) lib/grape/middleware/base.rb:19:in`call'
  ....

how can we add/send status with no response....

**Comment by gottfrois** [comment]
Can you show me your endpoint definition please?

**Comment by vijay22** [comment]
resource :getrecords do        

```
   throttle max: 10, per: 1.minute
desc "List all the member"
get do          
   if params[:email].present?
      js = User.where(email: params[:email]).paginate(page: 1)
      status js.present? ? :ok : 204
      response(js)
   else
     status 204
   end          
end
```

end

when code is in the else part or when there is no data .. it breaks 
i guess status is creating some issue... do you have any suggestion

**Comment by gottfrois** [comment]
Hm looking at your code no, I'll need to investigate a bit more.

**Comment by gottfrois** [comment]
Can you try with latest version? `v0.3.0`

**Comment by vijay22** [comment]
hi it got fixed with  the update..
thanks

**Comment by vijay22** [comment]
How do we need to set redis client url through env['REDIS_URL'] variable.
Where we need to write this code.
On server I am getting error Error connecting to Redis on localhost:6379 (Errno::ECONNREFUSED)

**Comment by gottfrois** [comment]
On your server, you just want to set the `REDIS_URL` env variable to your production redis database url :)

**Comment by vijay22** [comment]
A question - can we use grape-attack other than grape API.. i.e., for any methods.
for eg in rack attak we can use the path
Rack::Attack.throttle('api/json/members')

**Comment by gottfrois** [comment]
Well the gem has been designed to work for Grape. Do you have a concrete example in mind? Otherwise rack-attack is a great gem as well.
